// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGxtze0iNZ_X7TqtGNcV4j9HSyzqky28Y',
    appId: '1:873485441003:web:c963050f8c740f78822bae',
    messagingSenderId: '873485441003',
    projectId: 'simpleswap-48af1',
    authDomain: 'simpleswap-48af1.firebaseapp.com',
    storageBucket: 'simpleswap-48af1.appspot.com',
    measurementId: 'G-S2Z3756DE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9HB37rRmF5iFX5-vfjYhGRNtKMtCt-2o',
    appId: '1:873485441003:android:88743f3e8983b919822bae',
    messagingSenderId: '873485441003',
    projectId: 'simpleswap-48af1',
    storageBucket: 'simpleswap-48af1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD01k3CiuvCfHjuHFas7TL-KCyBkWhcxxc',
    appId: '1:873485441003:ios:5e483f3eca4ec8ba822bae',
    messagingSenderId: '873485441003',
    projectId: 'simpleswap-48af1',
    storageBucket: 'simpleswap-48af1.appspot.com',
    iosClientId: '873485441003-u57vmneih3hpsgnb0jp8cgbp1mvq7i2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD01k3CiuvCfHjuHFas7TL-KCyBkWhcxxc',
    appId: '1:873485441003:ios:5e483f3eca4ec8ba822bae',
    messagingSenderId: '873485441003',
    projectId: 'simpleswap-48af1',
    storageBucket: 'simpleswap-48af1.appspot.com',
    iosClientId: '873485441003-u57vmneih3hpsgnb0jp8cgbp1mvq7i2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGxtze0iNZ_X7TqtGNcV4j9HSyzqky28Y',
    appId: '1:873485441003:web:15e12e23546c4051822bae',
    messagingSenderId: '873485441003',
    projectId: 'simpleswap-48af1',
    authDomain: 'simpleswap-48af1.firebaseapp.com',
    storageBucket: 'simpleswap-48af1.appspot.com',
    measurementId: 'G-X4F5CGPY85',
  );

}